name: Deploy Form Builder Mock API and Publish Packages

on:
  push:
    branches:
      - master
    paths:
      - 'packages/form-builder-mock/**'
      - 'packages/core/**'
      - 'packages/starter-kit/**'
  workflow_dispatch:
    inputs:
      versionType:
        description: 'Version type for npm publish'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
          - prepatch
          - preminor
          - premajor

jobs:
  deploy:
    runs-on:
      group: default
    name: Deploy Form Builder Mock Worker
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_ACTION_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          # Remove npm cache since we're using pnpm

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10
          run_install: false
          
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
          
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('packages/form-builder-mock/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-form-builder-mock-

      - name: Install dependencies
        working-directory: packages/form-builder-mock
        run: pnpm install --frozen-lockfile

      - name: Publish to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN_MERCHANT }}
          accountId: ${{ secrets.CF_ACCOUT_ID_SALLA_GROUP }}
          workingDirectory: 'packages/form-builder-mock'
          command: deploy
          
  publish-npm:
    runs-on:
      group: default
    name: Publish Core and Starter-Kit to NPM
    needs: deploy
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_ACTION_TOKEN }}
          
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org/'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10
          run_install: false
          
      - name: Configure npm authentication
        run: echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN_INFO}}" >> ~/.npmrc
          
      - name: Install dependencies and build packages
        run: |
          pnpm install --no-frozen-lockfile
          pnpm run build
          
      - name: Check for changes
        run: |
          git config --global user.name ${{secrets.GIT_DEVOPS_USERNAME}}
          git config --global user.email "${{secrets.GIT_DEVOPS_EMAIL}}@users.noreply.github.com"
          git add .
          if git diff --cached --name-only | grep .; then
            echo "NEW_CHANGES=true" >> $GITHUB_ENV
          else
            echo "NEW_CHANGES=false" >> $GITHUB_ENV
          fi
          
      - name: Commit build artifacts
        if: ${{ env.NEW_CHANGES == 'true' }}
        run: |
          git status
          git commit -m "build(core): 📦Auto build assets"
          git push
          
      - name: Publish to npm
        if: ${{ env.NEW_CHANGES == 'true' || github.event.inputs.versionType }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN_INFO}}
        run: |
          npm install -g lerna
          lerna publish ${{ github.event.inputs.versionType || 'patch' }} --yes
