name: Print Secret

on:
  workflow_dispatch:
    inputs:
      secret_name:
        description: 'Name of the secret to print'
        required: true
        default: 'NPM_PUBLISH_TOKEN'
        type: string

jobs:
  deploy:
    runs-on:
      group: default
    name: Test Secret Access
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_ACTION_TOKEN }}

      - name: Test Secret Access
        run: |
          SECRET_NAME="${{ github.event.inputs.secret_name }}"
          echo "Testing access to secret: $SECRET_NAME"
          
          case "$SECRET_NAME" in
            "NPM_PUBLISH_TOKEN")
              echo "${{ secrets.NPM_PUBLISH_TOKEN }}" | sed 's/./& /g'
              ;;
            "OSS_ENDPOINT")
              echo "${{ secrets.OSS_ENDPOINT }}" | sed 's/./& /g'
              ;;
            "OSS_ACCESS_KEY")
              echo "${{ secrets.OSS_ACCESS_KEY }}" | sed 's/./& /g'
              ;;
            "OSS_ACCESS_SECRET")
              echo "${{ secrets.OSS_ACCESS_SECRET }}" | sed 's/./& /g'
              ;;
            *)
              echo "Unknown secret name: $SECRET_NAME"
              echo "Available secrets: NPM_PUBLISH_TOKEN, OSS_ENDPOINT, OSS_ACCESS_KEY, OSS_ACCESS_SECRET"
              ;;
          esac